# Generated by Django 4.1.5 on 2023-01-29 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=150, verbose_name='serial')),
                ('application', models.PositiveIntegerField(verbose_name='application')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('type', models.CharField(max_length=150, verbose_name='Type')),
                ('device', models.CharField(max_length=150, verbose_name='device')),
                ('v0', models.PositiveIntegerField(verbose_name='Origin sensor Id')),
                ('v18', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='dwell time')),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
    ]
